### ISSUE TITLE
Schema name in Transform Page should be editable

### ISSUE THREAD

**Issue by Abhishek-N** [DalgoT4D/DDP_backend#571]
Faced issue on STIR, updating the schema name was not possible

**Comment by fatchat** [comment]
Repo and schema should both be editable... didn't this used to be the case @Ishankoradia ? am i mis-remembering this

**Comment by Ishankoradia** [comment]
> Faced issue on STIR, updating the schema name was not possible

Hey @fatchat no, i do see some api in our backend but i dont think we have exposed this functionality of updating `Target schem` or `git repo`

**Comment by Ishankoradia** [comment]
> @Ishankoradia ok let's do this then
> 
> for the schema do we update `DbtCliProfile.target` or `DbtCliProfile.target_configs.schema` or both

Ideally we should only be updating `DbtCliProfile.target_configs.schema` but since we have kept both the values same for some reason. So we will need to update both.

This is how the `profiles.yml` looks like. The `dbtrepo.outputs.schema` is same as `dbtrepo.target` and this value is stored in `OrgDbt.default_schema`. 
```
config: {}
dbtrepo:
  outputs:
    intermediate:
      dbname: ****
      host: localhost
      password: ****
      port: 5432
      schema: intermediate
      threads: 4
      type: postgres
      user: postgres
  target: intermediate
```
I think its a good point to distinguish them. In our usecase, we wont ever update `dbtrepo.target` however we have use at many place while executing dbt `--target {default_schema}` which might need to replaced carefully if we are going to distinguish them. Shouldn't be terrible though.
