### ISSUE TITLE
Commcare Connector Changes

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/DDP_backend#946]
For API Key field, we need to add some text/a hint which lets users know that when adding in API Key you put it in as "user id:API Key". Org like shofco will start using it soon so we need to make sure they can understand without our help. or any other NGO in future.

**Comment by fatchat** [comment]
our `spec.yaml` contains

```
    api_key:
      type: string
      title: "Username:API Key"
      description: >-
        Commcare username with API Key, colon-separated
      airbyte_secret: true
      order: 0
```

we have to figure out why this isn't showing up in our form
